# Generated by Django 5.1.1 on 2024-09-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_categroy_options_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categroy',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Categroy',
            new_name='Category',
        ),
    ]
